name: "Set Bug Issue Label and Assignee"
on:
  issues:
    types: [opened]

jobs:
  autoassign:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["[BUG]", "bug"], "labels": ["bug :bug:"], "assignees": ["antalszava"]}, {"keywords": ["[unitaryHACK]", "[unitaryhack]"], "labels": ["unitaryhack"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
